push

diff --git a/staging/ecr-credential-helper.yaml b/staging/ecr-credential-helper.yaml
--- a/staging/ecr-credential-helper.yaml
+++ b/staging/ecr-credential-helper.yaml
@@ -60,6 +60,11 @@ spec:
               #!/bin/bash
               set -e
               
+              echo "Installing kubectl..."
+              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+              chmod +x kubectl
+              mv kubectl /usr/bin/kubectl || mv kubectl /usr/local/bin/kubectl || (echo "Could not move kubectl to system path, using local ./kubectl" && export PATH=$PATH:.)
+              
               echo "Getting ECR authorization token..."
               TOKEN=$(aws ecr get-login-password --region ${REGION})
               
@@ -81,5 +86,13 @@ spec:
                 --docker-username=AWS \
                 --docker-password="${TOKEN}" \
                 --namespace=argocd
+              
+              echo "Creating secret in production namespace..."
+              kubectl delete secret ecr-registry-secret -n production --ignore-not-found
+              kubectl create secret docker-registry ecr-registry-secret \
+                --docker-server=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com \
+                --docker-username=AWS \
+                --docker-password="${TOKEN}" \
+                --namespace=production
               
               echo "Done!"
